# backend:
#   name: "github"
#   repo: "amessinger/gallery"
backend:
  name: test-repo

media_folder: "images"

collections:
  - name: "series"
    label: "Series"
    folder: "series"
    create: true
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "markdown"
      - name: "photos"
        label: "Photos"
        widget: "list"
        fields:
          - name: "image"
            label: "Image"
            widget: "image"
          - name: "title"
            label: "Title"
            widget: "string"
          - name: "comment"
            label: "Comment"
            widget: "string"
            required: false
