backend:
  name: "github"
  repo: "amessinger/gallery"

media_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "index"
        label: "Index"
        file: "index.md"
        fields:
          - name: "cover"
            label: "Cover"
            widget: "image"
      - name: "about"
        label: "About"
        file: "about.md"
        fields:
          - name: "about"
            label: "About"
            widget: "markdown"
          - name: "instagram"
            label: "Instagram"
            widget: "string"
      - name: "contact"
        label: "Contact"
        file: "contact.md"
        fields:
          - name: "email"
            label: "Email address"
            widget: "string"
          - name: "success"
            label: "Success message"
            widget: "string"
          - name: "failure"
            label: "Failure message"
            widget: "string"

  - name: "series"
    label: "Series"
    folder: "series"
    create: true
    slug: "{{title}}"
    editor:
      preview: false
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "description"
        label: "Description"
        widget: "markdown"
      - name: "photos"
        label: "Photos"
        widget: "list"
        fields:
          - name: "image"
            label: "Image"
            widget: "image"
          - name: "title"
            label: "Title"
            widget: "string"
          - name: "comment"
            label: "Comment"
            widget: "string"
            required: false
